version: '3.8'

services:
  acum:
    container_name: acum
    image: 'acum:0.0.1-SNAPSHOT'
    environment:
      POSTGRESQL_PORT: 5432
      POSTGRESQL_HOST: db
    depends_on:
      - db
    restart: always
    ports:
      - '8080:8080'

  db:
    image: bitnami/postgresql:15
    container_name: postgres-db
    hostname: db
    environment:
      - POSTGRESQL_DATABASE=acum
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./acum/src/main/resources/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
      - ./acum/src/main/resources/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
      - ./acum/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  postgres_data: